import { ReproContext } from '@/context';

const { writeFileSync, mkdirSync, existsSync } = require('fs');

export async function generateLoginFlow(ctx: ReproContext): Promise<ReproContext> {
  if (!ctx.loginFlow) {
    return ctx;
  }

  console.log('   🔐 Generating login flow...');

  const flowDir = ctx.flowDir;
  if (!existsSync(flowDir)) {
    mkdirSync(flowDir, { recursive: true });
  }

  const loginFlowFile = `${flowDir}/login-flow.yaml`;

  const yaml = generateLoginYaml(ctx);

  writeFileSync(loginFlowFile, yaml);

  console.log(`   ✅ Login flow saved to: ${loginFlowFile}`);

  return ctx;
}

function generateLoginYaml(ctx: ReproContext): string {
  const { emailField, passwordField, loginButton } = ctx.loginFlow!;
  const { email, password } = ctx.credentials!;

  let yaml = `# Login flow - auto-generated by repro\n`;
  yaml += `# Platform: ${ctx.platform}\n`;
  yaml += `# App: ${ctx.appId}\n\n`;
  yaml += `appId: ${ctx.appId}\n`;
  yaml += `platform: ${ctx.platform}\n`;
  yaml += `---\n`;
  yaml += `- tapOn: "${emailField}"\n`;
  yaml += `- inputText:\n`;
  yaml += `    text: "${email}"\n`;
  yaml += `- tapOn: "${passwordField}"\n`;
  yaml += `- inputText:\n`;
  yaml += `    text: "${password}"\n`;
  yaml += `- tapOn: "${loginButton}"\n`;

  return yaml;
}
